modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "CC BY-NC-ND 4.0"

[[mods]]
modId = "cristellib"
version = "${version}"
displayName = "Cristel Lib"
authors = "Cristelknight999"
description = '''
A Library mod for easy structure config and runtime datapacks.
'''
logoFile = "assets/cristellib/textures/icon.png"

[[dependencies.cristellib]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cristellib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"