minecraft_version=26.1.2
minecraft_versions=26.1, 26.1.1, 26.1.2

# Project
mod_id=cristellib
version=3.1.4
group=de.cristelknight.cristellib
java_version=25

## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1


# Dependencies https://github.com/LlamaLad7/MixinExtras/releases
mixinextras_version=0.5.4
jankson_version=1.2.3

# Mod Menu https://modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0-beta.1

# Cloth Config https://modrinth.com/mod/cloth-config/versions
cloth_config_version=26.1.154


# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_api_version=0.148.2+26.1.2
fabric_loader_version=0.19.2
fabric_loader_min_version=0.18.5
quilt_loader_version=0.30.0-beta.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.48-beta
neoforge_loader_version_range=[4,)

# Mod Properties
mod_name=Cristel Lib

### https://creativecommons.org/licenses/by-nc-sa/4.0/
license=CC-BY-NC-ND-4.0
mod_author=Cristelknight
description=A Library mod for easy structure config and runtime datapacks.
homepage=https://modrinth.com/mod/cristel-lib
sources=https://github.com/Cristelknight999/Cristel-Lib
issues=https://github.com/Cristelknight/Cristel-Lib/issues

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
