plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'com.hypherionmc.modutils.modpublisher'
}
dependencies {
    implementation("me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}")
    jarJar(implementation("blue.endless:jankson:${jankson_version}"))
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file("runs/client"))
        }
        data {
            clientData()
            gameDirectory = this.mkdir(this.file("runs/data"))
            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            this.file("runs/server").createParentDirectories()
            gameDirectory = this.mkdir(this.file("runs/server"))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

publisher {
    // Setup the required API keys. You only need to define the keys for
    // the platforms you plan on uploading to
    apiKeys {
        modrinth (providers.gradleProperty("modrinthToken").orElse(System.getenv("MODRINTH_TOKEN")).get())
        curseforge (providers.gradleProperty("curseToken").orElse(System.getenv("CURSE_TOKEN")).get())
    }

    // Enable Debug mode. When enabled, no files will actually be uploaded
    setDebug(false)

    // Curseforge Project ID
    setCurseID("856996")

    // Modrinth Project ID
    setModrinthID("cl223EMc")

    // Type of release. beta, alpha or release
    // You can also use VersionType.BETA, VersionType.ALPHA or VersionType.RELEASE
    setVersionType("release")

    // Required for Modrinth/GitHub
    setProjectVersion("neoforge-${rootProject.minecraft_version}-${project.version}")

    // Fancy display name for the upload.
    // Will default to the project version if not set
    setDisplayName("Cristel Lib ${project.version}")

    // The supported game versions
    String[] versions = minecraft_versions.tokenize(",").collect{ it.trim()}.toArray()
    setGameVersions(versions)

    // The modloaders your upload supports.
    // This can also be an Enum from ModLoader,
    // like setLoaders(ModLoader.FABRIC, ModLoader.FORGE)
    setLoaders("neoforge")

    // The new Curseforge Environment tag. Optional
    // Valid values are "server", "client" or "both"
    // You can also use CurseEnvironment.BOTH, or CurseEnvironment.SERVER or CurseEnvironment.CLIENT
    setCurseEnvironment("both")

    // Upload the release, but keep it "private" until you are ready
    // Unreleased feature on CurseForge, working on Modrinth
    setIsManualRelease(false)

    // The file to be uploaded. This can be a file, task, or string.
    // setArtifact("build/libs/mymod.jar")
    // setArtifact(jar.getArchiveFile().get())
    // If this is a task, the task specified will be executed before publishing
    setArtifact(tasks.jar)

    // Disable the built in Fractureizer scanner
    setDisableMalwareScanner(true)

    curseDepends {
        required "cloth-config"
    }
    modrinthDepends {
        required "cloth-config"
    }



    // Add supported java versions. Currently only used by CurseForge
    // Supports anything that can be parsed using JavaVersion.toVersion()
    setJavaVersions([JavaVersion.toVersion(java_version)])
}

/* Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}
 */
