package de.cristelknight.cristellib;

import com.google.common.base.Supplier;
import com.google.common.base.Suppliers;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import de.cristelknight.cristellib.config.ConfigManager;
import de.cristelknight.cristellib.config.ConfigType;
import de.cristelknight.cristellib.config.structure.ReadStructureSets;
import de.cristelknight.cristellib.config.structure.ed.ToggleConfig;
import de.cristelknight.cristellib.config.structure.placement.PlacementConfig;
import de.cristelknight.cristellib.data.codec.StructureSetData;
import de.cristelknight.cristellib.util.FileHelper;
import de.cristelknight.cristellib.util.JsonHelper;
import de.cristelknight.cristellib.util.runtimepack.RuntimePackUtil;
import net.minecraft.resources.Identifier;
import net.minecraft.server.packs.PackType;

import java.nio.file.Path;
import java.util.*;
import java.util.Collection;

public abstract class StructureConfig {

    public static final Codec<StructureConfig> CODEC = RecordCodecBuilder.create(builder ->
            builder.group(
                    Codec.STRING.fieldOf("name").forGetter(config -> FileHelper.fileName(config.getPath())),
                    Codec.STRING.fieldOf("path").forGetter(config -> String.valueOf(config.path.getParent())),
                    Codec.STRING.optionalFieldOf("header", "").forGetter(config -> config.header),
                    ConfigType.CODEC.fieldOf("config_type").forGetter(config -> config.type),
                    Codec.unboundedMap(Codec.STRING, Codec.STRING).optionalFieldOf("comments", new HashMap<>()).forGetter(config -> config.comments),
                    Codec.list(StructureSetData.CODEC).fieldOf("structure_sets").forGetter(config -> config.structureSetHolders)
            ).apply(builder, ((s, s2, s3, configType, stringStringMap, structureSetData) ->
                    configType == ConfigType.ENABLE_DISABLE ?
                            new StructureConfigToggle(s, s2, s3, stringStringMap, structureSetData) :
                            new StructureConfigPlacement()))
    );

    protected static final Set<Identifier> modifiedSets = new HashSet<>();

    // Codec

    private final Path path;

    private String header = "";

    private ConfigType type;

    private Map<String, String> comments;

    private final List<StructureSetData> structureSetHolders;

    // Internal
    private String defaultNamespace = "";

    private boolean isAutoGenerated = false;

    // default values

    // current values (structure_set + Config)
    private Map<Identifier, ToggleConfig> enableDisableConfig = null;
    private Map<Identifier, PlacementConfig> placementConfig = null;

    private StructureConfig(String name, String path, String header, Map<String, String> comments, List<StructureSetData> structureSetHolders) { // for CODEC
        this(FileHelper.janksonPathFromString(path, name), header, comments, structureSetHolders);
    }

    StructureConfig(Path path, String header, Map<String, String> comments, List<StructureSetData> structureSetHolders) {
        this.path = path;
        if (header != null && !header.isEmpty()) setHeader(header);
        this.comments = comments;
        this.structureSetHolders = structureSetHolders;

        if (!this.structureSetHolders.isEmpty())
            setDefaultNamespace();
    }

    void addSet(StructureSetData set) {
        structureSetHolders.add(set);
    }


    public static void addSetsToRuntimePack(Collection<StructureConfig> configs) {
        modifiedSets.clear();
        configs.forEach(StructureConfig::applyToRuntimePack);
    }

    private void applyToRuntimePack() {
        readConfig(false);
        checkForError();

        structureSetHolders.forEach(holder -> holder.sets().forEach(setLocation -> {
            String modId = holder.modId();

            boolean differsFromDefault = add(modId, setLocation);
            if (!differsFromDefault && !modifiedSets.contains(setLocation))
                CristelLib.CONFIG_PACK.removeStructureSet(setLocation);
        }));
    }

    public abstract boolean add(String modId, Identifier setLocation);

    JsonElement getStructureSet(Identifier location, String modId) {
        Identifier structureLocation = RuntimePackUtil.getLocationForStructureSet(location);
        if (CristelLib.CONFIG_PACK.hasData(structureLocation)) {
            return CristelLib.CONFIG_PACK.getResourceAsJson(PackType.SERVER_DATA, structureLocation);
        }
        return JsonHelper.getSetElement(location, modId);
    }

    /**
     * Writes the configuration to the filesystem.
     * This method initializes the structures or placements depending on the {@link ConfigType}.
     */
    public void writeConfig(boolean override) {
        if (!override && getPath().toFile().exists()) return;

        if (type.equals(ConfigType.ENABLE_DISABLE)) {
            ConfigManager.createToggleConfig(this);
        } else if (type.equals(ConfigType.PLACEMENT)) {
            ConfigManager.createPlacementConfig(this);
        }
    }

    public abstract void readConfig(boolean override);


    // API
    public static StructureConfig create(Path path, ConfigType type) {
        return type.equals(ConfigType.ENABLE_DISABLE) ? new StructureConfigToggle() : new StructureConfigPlacement();
    }

    public static StructureConfig create(Path path, String name, ConfigType type) {
        return new StructureConfig(path.resolve(name + ".json5"), type);
    }

    public static StructureConfig createWithDefaultConfigPath(String subPath, String name, ConfigType type) {
        return new StructureConfig(CristelLibExpectPlatform.getConfigDirectory().resolve(subPath).resolve(name + ".json5"), type);
    }

    public static StructureConfig createWithDefaultConfigPath(String name, ConfigType type) {
        return new StructureConfig(CristelLibExpectPlatform.getConfigDirectory().resolve(name + ".json5"), type);
    }

    public void setComments(Map<String, String> comments) {
        this.comments = comments;
    }

    public void setHeader(String header) {
        this.header = header;
    }

    public String getHeader() {
        return header;
    }

    public Map<String, String> getComments() {
        return comments;
    }

    public Map<Identifier, List<Identifier>> getDefaultStructures() {
        return structuresForED.get();
    }

    public Map<Identifier, PlacementConfig> getDefaultStructurePlacement() {
        return structurePlacement.get();
    }

    public Path getPath() {
        return path;
    }

    public ConfigType getType() {
        return type;
    }

    public Identifier toDefaultId(String id) {
        if (id.contains(":")) return Identifier.parse(id);
        else if (defaultNamespace.equals(Constants.MC_ID)) return Identifier.withDefaultNamespace(id);
        else return Identifier.fromNamespaceAndPath(defaultNamespace, id);
    }

    public String toDefaultString(Identifier id) {
        return id.getNamespace().equals(defaultNamespace)
                ? id.getPath()
                : id.toString();
    }

    public void setDefaultNamespace() {
        Map<String, Integer> namespaceCounts = new HashMap<>();

        for (StructureSetData data : structureSetHolders) {
            for (Identifier set : data.sets()) {
                namespaceCounts.merge(set.getNamespace(), 1, Integer::sum);
            }
        }

        if (namespaceCounts.isEmpty()) {
            throw new RuntimeException("No namespaces found in config with path: " + getPath() + " :(((");
        }

        this.defaultNamespace = namespaceCounts.entrySet().stream()
                .max(Map.Entry.comparingByValue())
                .map(Map.Entry::getKey)
                .orElseThrow(() -> new RuntimeException("Could not determine default namespace :((("));
    }

    public boolean isSetsEmpty() {
        return structureSetHolders.isEmpty();
    }

    public Map<Identifier, ToggleConfig> getEnableDisableConfig() {
        return enableDisableConfig;
    }

    public Map<Identifier, PlacementConfig> getPlacementConfig() {
        return placementConfig;
    }

    public void updateEDConfig(Identifier key, ToggleConfig config) {
        this.enableDisableConfig.put(key, config);
    }

    public void updatePlacement(Identifier key, PlacementConfig config) {
        this.placementConfig.put(key, config);
    }

    private static void clearModifiedSets() {
        modifiedSets.clear();
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated() {
        isAutoGenerated = true;
    }

    private void checkForError() {
        Set<Identifier> setsToCheck = type.equals(ConfigType.ENABLE_DISABLE) ? enableDisableConfig.keySet() : placementConfig.keySet();

        boolean error = false;
        for (StructureSetData data : structureSetHolders) {
            List<Identifier> newlyReadSets = data.sets();
            if (!setsToCheck.containsAll(newlyReadSets)) {
                error = true;
                var missing = new ArrayList<>(newlyReadSets);
                missing.removeAll(setsToCheck);
                Constants.LOG.error("Structure sets are missing from config: {}", missing);
            }
        }
        if (!error) return;

        enableDisableConfig = null;
        placementConfig = null;
        String name = FileHelper.fileName(path);
        FileHelper.renameFile(path, name + "-had-error");
        writeConfig(true);
        readConfig(true);
    }
}