package de.cristelknight.cristellib;

import com.google.gson.JsonElement;
import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import de.cristelknight.cristellib.config.ConfigType;
import de.cristelknight.cristellib.data.codec.StructureSetData;
import de.cristelknight.cristellib.util.FileHelper;
import de.cristelknight.cristellib.util.JsonHelper;
import de.cristelknight.cristellib.util.runtimepack.RuntimePackUtil;
import net.minecraft.resources.Identifier;
import net.minecraft.server.packs.PackType;

import java.nio.file.Path;
import java.util.*;

public abstract class StructureConfig {

    public static final Codec<StructureConfig> CODEC = RecordCodecBuilder.create(builder ->
            builder.group(
                    Codec.STRING.fieldOf("name").forGetter(config -> FileHelper.fileName(config.getPath())),
                    Codec.STRING.fieldOf("path").forGetter(config -> String.valueOf(config.path.getParent())),
                    Codec.STRING.optionalFieldOf("header", "").forGetter(config -> config.header),
                    ConfigType.CODEC.fieldOf("config_type").forGetter(StructureConfig::getType),
                    Codec.unboundedMap(Codec.STRING, Codec.STRING).optionalFieldOf("comments", new HashMap<>()).forGetter(config -> config.comments),
                    Codec.list(StructureSetData.CODEC).fieldOf("structure_sets").forGetter(config -> config.structureSetHolders)
            ).apply(builder, ((n, p, h, configType, c, s) ->
                    configType == ConfigType.TOGGLE ?
                            new StructureConfigToggle(n, p, h, c, s) :
                            new StructureConfigPlacement(n, p, h, c, s)
            ))
    );

    private static final Set<Identifier> modifiedSets = new HashSet<>();

    // Codec
    private final Path path;

    private String header = "";

    private Map<String, String> comments;

    private final List<StructureSetData> structureSetHolders;

    // Internal
    private String defaultNamespace = "";

    private boolean isAutoGenerated = false;

    StructureConfig(Path path, String header, Map<String, String> comments, List<StructureSetData> structureSetHolders) {
        this.path = path;
        if (header != null && !header.isEmpty()) setHeader(header);
        this.comments = comments;
        this.structureSetHolders = structureSetHolders;

        if (!this.structureSetHolders.isEmpty())
            setDefaultNamespace();
    }

    void addSet(StructureSetData set) {
        structureSetHolders.add(set);
    }


    public static void addSetsToRuntimePack(Collection<StructureConfig> configs) {
        CristelLib.CONFIG_PACK.clear(PackType.SERVER_DATA);
        modifiedSets.clear();
        configs.forEach(StructureConfig::applyToRuntimePack);
    }

    private void applyToRuntimePack() {
        readConfig(false);
        checkForError();

        structureSetHolders.forEach(holder -> holder.sets().forEach(setLocation -> {
            String modId = holder.modId();

            boolean differsFromDefault = addChanges(modId, setLocation);
            if (differsFromDefault)
                modifiedSets.add(setLocation);
            else if (!modifiedSets.contains(setLocation))
                CristelLib.CONFIG_PACK.removeStructureSet(setLocation);
        }));
    }

    public abstract boolean addChanges(String modId, Identifier setLocation);

    public static JsonElement getStructureSet(Identifier location, String modId) {
        Identifier structureLocation = RuntimePackUtil.getLocationForStructureSet(location);
        if (CristelLib.CONFIG_PACK.hasData(structureLocation)) {
            return CristelLib.CONFIG_PACK.getResourceAsJson(PackType.SERVER_DATA, structureLocation);
        }
        return JsonHelper.getSetElement(location, modId);
    }

    // TODO:
    private void checkForError() {
        Set<Identifier> setsToCheck = getConfigKeys();

        boolean error = false;
        for (StructureSetData data : structureSetHolders) {
            List<Identifier> newlyReadSets = data.sets();
            if (!setsToCheck.containsAll(newlyReadSets)) {
                error = true;
                var missing = new ArrayList<>(newlyReadSets);
                missing.removeAll(setsToCheck);
                Constants.LOG.error("Structure sets are missing from config: {}", missing);
            }
        }
        if (!error) return;

        resetConfigs();
        String name = FileHelper.fileName(path);
        FileHelper.renameFile(path, name + "-had-error");
        writeConfig(true);
        readConfig(true);
    }

    /**
     * Writes the configuration to the filesystem.
     * This method initializes the structures or placements depending on the {@link ConfigType}.
     */
    public abstract void writeConfig(boolean override);

    public abstract void readConfig(boolean override);


    // API
    public static StructureConfig create(Path path, ConfigType type) {
        return type == ConfigType.TOGGLE ? new StructureConfigToggle(path) : new StructureConfigPlacement(path);
    }

    public static StructureConfig create(Path path, String name, ConfigType type) {
        Path fullPath = path.resolve(name + ".json5");
        return create(fullPath, type);
    }

    public static StructureConfig createWithDefaultConfigPath(String subPath, String name, ConfigType type) {
        Path fullPath = CristelLibExpectPlatform.getConfigDirectory().resolve(subPath).resolve(name + ".json5");
        return create(fullPath, type);
    }

    public static StructureConfig createWithDefaultConfigPath(String name, ConfigType type) {
        Path fullPath = CristelLibExpectPlatform.getConfigDirectory().resolve(name + ".json5");
        return create(fullPath, type);
    }

    public void setComments(Map<String, String> comments) {
        this.comments = comments;
    }

    public void setHeader(String header) {
        this.header = header;
    }

    public String getHeader() {
        return header;
    }

    public Map<String, String> getComments() {
        return comments;
    }

    public Path getPath() {
        return path;
    }

    public abstract ConfigType getType();

    public Identifier toDefaultId(String id) {
        if (id.contains(":")) return Identifier.parse(id);
        else if (defaultNamespace.equals(Constants.MC_ID)) return Identifier.withDefaultNamespace(id);
        else return Identifier.fromNamespaceAndPath(defaultNamespace, id);
    }

    public String toDefaultString(Identifier id) {
        return id.getNamespace().equals(defaultNamespace)
                ? id.getPath()
                : id.toString();
    }

    public void setDefaultNamespace() {
        Map<String, Integer> namespaceCounts = new HashMap<>();

        for (StructureSetData data : structureSetHolders) {
            for (Identifier set : data.sets()) {
                namespaceCounts.merge(set.getNamespace(), 1, Integer::sum);
            }
        }

        if (namespaceCounts.isEmpty()) {
            throw new RuntimeException("No namespaces found in config with path: " + getPath() + " :(((");
        }

        this.defaultNamespace = namespaceCounts.entrySet().stream()
                .max(Map.Entry.comparingByValue())
                .map(Map.Entry::getKey)
                .orElseThrow(() -> new RuntimeException("Could not determine default namespace :((("));
    }

    public boolean setsNotEmpty() {
        return !structureSetHolders.isEmpty();
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated() {
        isAutoGenerated = true;
        setHeader("Automatically generated by Cristel Lib");
    }

    public abstract Set<Identifier> getConfigKeys();

    public abstract void resetConfigs();
}