package de.cristelknight.cristellib;

import com.google.common.base.Supplier;
import com.google.common.base.Suppliers;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import de.cristelknight.cristellib.config.ConfigManager;
import de.cristelknight.cristellib.config.ConfigType;
import de.cristelknight.cristellib.config.structure.ReadStructureSets;
import de.cristelknight.cristellib.config.structure.ed.EDConfig;
import de.cristelknight.cristellib.config.structure.placement.PlacementConfig;
import de.cristelknight.cristellib.data.codec.StructureSetData;
import de.cristelknight.cristellib.util.FileHelper;
import de.cristelknight.cristellib.util.JsonHelper;
import de.cristelknight.cristellib.util.runtimepack.RuntimePackUtil;
import net.minecraft.resources.Identifier;
import net.minecraft.server.packs.PackType;

import java.nio.file.Path;
import java.util.*;

public class StructureConfig {

    public static final Codec<StructureConfig> CODEC = RecordCodecBuilder.create(builder ->
            builder.group(
                    Codec.STRING.fieldOf("name").forGetter(config -> FileHelper.fileName(config.getPath())),
                    Codec.STRING.fieldOf("path").forGetter(config -> String.valueOf(config.path.getParent())),
                    Codec.STRING.optionalFieldOf("header", "").forGetter(config -> config.header),
                    ConfigType.CODEC.fieldOf("config_type").forGetter(config -> config.type),
                    Codec.unboundedMap(Codec.STRING, Codec.STRING).optionalFieldOf("comments", new HashMap<>()).forGetter(config -> config.comments),
                    Codec.list(StructureSetData.CODEC).fieldOf("structure_sets").forGetter(config -> config.structureSetHolders)
            ).apply(builder, StructureConfig::new)
    );

    private static final Set<Identifier> modifiedSets = new HashSet<>();

    // Codec

    private final Path path;

    private String header = "";

    private final ConfigType type;

    private Map<String, String> comments;

    private final List<StructureSetData> structureSetHolders;

    // Internal
    private String defaultNamespace = "";

    private boolean isAutoGenerated = false;

    // default values
    private final Supplier<Map<Identifier, List<Identifier>>> structuresForED;
    private final Supplier<Map<Identifier, PlacementConfig>> structurePlacement;

    // current values (structure_set + Config)
    public Map<Identifier, EDConfig> enableDisableConfig = null;
    public Map<Identifier, PlacementConfig> placementConfig = null;


    private StructureConfig(Path path, ConfigType type) {
        this(path, null, new HashMap<>(), type, new ArrayList<>());
    }

    private StructureConfig(String name, String path, String header, ConfigType type, Map<String, String> comments, List<StructureSetData> structureSetHolders) { // for CODEC
        this(FileHelper.janksonPathFromString(path, name), header, comments, type, structureSetHolders);
    }

    private StructureConfig(Path path, String header, Map<String, String> comments, ConfigType type, List<StructureSetData> structureSetHolders) {
        this.path = path;
        if (header != null && !header.isEmpty()) setHeader(header);
        this.comments = comments;
        this.type = type;
        this.structureSetHolders = structureSetHolders;

        if (!this.structureSetHolders.isEmpty())
            setDefaultNamespace();

        this.structuresForED = Suppliers.memoize(() -> ReadStructureSets.readSetsAndAddStructures(structureSetHolders));
        this.structurePlacement = Suppliers.memoize(() -> ReadStructureSets.readSetsAndAddPlacements(structureSetHolders));
    }

    void addSet(StructureSetData set) {
        structureSetHolders.add(set);
    }


    public void addSetsToRuntimePack() {
        readConfig(false);
        checkForError();

        structureSetHolders.forEach(holder -> holder.sets().forEach(setLocation -> {
            String modId = holder.modId();

            JsonElement structureSetElement = getStructureSet(setLocation, modId);
            if (!(structureSetElement instanceof JsonObject structureSet)) {
                Constants.LOG.warn("Set for {} {} is not a JsonObject, skipping...", modId, setLocation);
                return;
            }

            boolean changed = false;
            if (type.equals(ConfigType.ENABLE_DISABLE)) {
                if(removeStructureInSets(structureSet, setLocation)) changed = true;
            } else if (type.equals(ConfigType.PLACEMENT)) {
                if(updatePlacementsInSet(structureSet, setLocation, modId)) changed = true;
            }

            if (changed) {
                CristelLib.CONFIG_PACK.addStructureSet(setLocation, structureSet);
                modifiedSets.add(setLocation);
            } else if(!modifiedSets.contains(setLocation)) {
                CristelLib.CONFIG_PACK.removeStructureSet(setLocation);
            }
        }));
    }

    //TODO:
    private void checkForError() {
        Set<Identifier> setsToCheck = type.equals(ConfigType.ENABLE_DISABLE) ? enableDisableConfig.keySet() : placementConfig.keySet();

        boolean error = false;
        for (StructureSetData data : structureSetHolders) {
            List<Identifier> newlyReadSets = data.sets();
            boolean hasAll = setsToCheck.containsAll(newlyReadSets);
            if (!hasAll) {
                error = true;
                var newlyReadSetsCopy = new ArrayList<>(newlyReadSets);
                newlyReadSetsCopy.removeAll(setsToCheck);
                Constants.LOG.error("Structure sets are missing from config: {}", newlyReadSetsCopy);
                //break;
            }
        }
        if (!error) return;

        enableDisableConfig = null;
        placementConfig = null;
        String name = FileHelper.fileName(path);
        FileHelper.renameFile(path, name + "-had-error");
        writeConfig(true);
        readConfig(true);
    }

    private boolean removeStructureInSets(JsonObject structureSet, Identifier setLocation) {
        EDConfig setConfig = enableDisableConfig.get(setLocation);

        JsonArray array = structureSet.get("structures").getAsJsonArray();
        Iterator<JsonElement> structureIterator = array.iterator();
        while (structureIterator.hasNext()) {
            JsonElement structure = structureIterator.next();
            String structureName = toDefaultString(Objects.requireNonNull(Identifier.tryParse(structure.getAsJsonObject().get("structure").getAsString())));

            if (!setConfig.containsStructure(structureName)) {
                Constants.LOG.error("{} is not included in: {} for mod with path: {}", structureName, setLocation, path);
                continue;
            }

            if (setConfig.isStructureDisabled(structureName))
                structureIterator.remove();
        }

        return setConfig.hasDisabledStructure();
    }

    private boolean updatePlacementsInSet(JsonObject structureSet, Identifier setLocation, String modId) {
        PlacementConfig placementConfig = this.placementConfig.get(setLocation);
        JsonObject p = structureSet.get("placement").getAsJsonObject();

        p.addProperty("salt", placementConfig.salt());
        p.addProperty("spacing", placementConfig.spacing());
        p.addProperty("separation", placementConfig.separation());

        double newF = placementConfig.frequency();

        if ((p.has("frequency") || newF != 1.0) && (!p.has("frequency") || newF != p.get("frequency").getAsDouble()))
            p.addProperty("frequency", newF);

        if (!(JsonHelper.getSetElement(setLocation, modId) instanceof JsonObject copy))
            throw new RuntimeException(Constants.getWithPrefix(String.format(
                    "Couldn't get copy of structure set for %s from modId %s, can't check if placement was changed", setLocation, modId
            )));

        return !p.equals(copy.get("placement").getAsJsonObject());
    }

    private JsonElement getStructureSet(Identifier location, String modId) {
        Identifier structureLocation = RuntimePackUtil.getLocationForStructureSet(location);
        if (CristelLib.CONFIG_PACK.hasData(structureLocation)) {
            return CristelLib.CONFIG_PACK.getResourceAsJson(PackType.SERVER_DATA, structureLocation);
        }
        return JsonHelper.getSetElement(location, modId);
    }


    /**
     * Writes the configuration to the filesystem.
     * This method initializes the structures or placements depending on the {@link ConfigType}.
     */
    public void writeConfig(boolean override) {
        if (!override && getPath().toFile().exists()) return;

        if (type.equals(ConfigType.ENABLE_DISABLE)) {
            ConfigManager.createEDConfig(this, override);
        } else if (type.equals(ConfigType.PLACEMENT)) {
            ConfigManager.createPlacementConfig(this, override);
        }
    }

    public void readConfig(boolean override) {
        if (type.equals(ConfigType.ENABLE_DISABLE) && (enableDisableConfig == null || override))
            enableDisableConfig = ConfigManager.readEDConfig(this);
        else if (type.equals(ConfigType.PLACEMENT) && (placementConfig == null || override))
            placementConfig = ConfigManager.readPlacementConfig(this);
    }


    // API
    public static StructureConfig create(Path path, String name, ConfigType type) {
        return new StructureConfig(path.resolve(name + ".json5"), type);
    }

    public static StructureConfig createWithDefaultConfigPath(String subPath, String name, ConfigType type) {
        return new StructureConfig(CristelLibExpectPlatform.getConfigDirectory().resolve(subPath).resolve(name + ".json5"), type);
    }

    public static StructureConfig createWithDefaultConfigPath(String name, ConfigType type) {
        return new StructureConfig(CristelLibExpectPlatform.getConfigDirectory().resolve(name + ".json5"), type);
    }

    public void setComments(Map<String, String> comments) {
        this.comments = comments;
    }

    public void setHeader(String header) {
        this.header = header;
    }

    public String getHeader() {
        return header;
    }

    public Map<String, String> getComments() {
        return comments;
    }

    public Map<Identifier, List<Identifier>> getDefaultStructures() {
        return structuresForED.get();
    }

    public Map<Identifier, PlacementConfig> getDefaultStructurePlacement() {
        return structurePlacement.get();
    }

    public Path getPath() {
        return path;
    }

    public ConfigType getType() {
        return type;
    }

    public Identifier toDefaultId(String id) {
        if (id.contains(":")) return Identifier.parse(id);
        else if (defaultNamespace.equals(Constants.MC_ID)) return Identifier.withDefaultNamespace(id);
        else return Identifier.fromNamespaceAndPath(defaultNamespace, id);
    }

    public String toDefaultString(Identifier id) {
        return id.getNamespace().equals(defaultNamespace)
                ? id.getPath()
                : id.toString();
    }

    public void setDefaultNamespace() {
        Map<String, Integer> namespaceCounts = new HashMap<>();

        for (StructureSetData data : structureSetHolders) {
            for (Identifier set : data.sets()) {
                namespaceCounts.merge(set.getNamespace(), 1, Integer::sum);
            }
        }

        if (namespaceCounts.isEmpty()) {
            throw new RuntimeException("No namespaces found in config with path: " + getPath() + " :(((");
        }

        this.defaultNamespace = namespaceCounts.entrySet().stream()
                .max(Map.Entry.comparingByValue())
                .map(Map.Entry::getKey)
                .orElseThrow(() -> new RuntimeException("Could not determine default namespace :((("));
    }

    public boolean isSetsEmpty() {
        return structureSetHolders.isEmpty();
    }


    public static void clearModifiedSets() {
        modifiedSets.clear();
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated() {
        isAutoGenerated = true;
    }
}