package de.cristelknight.cristellib.config.client;

import com.mojang.datafixers.util.Pair;
import de.cristelknight.cristellib.CristelLib;
import de.cristelknight.cristellib.CristelLibExpectPlatform;
import de.cristelknight.cristellib.CristelLibRegistry;
import de.cristelknight.cristellib.StructureConfig;
import de.cristelknight.cristellib.autoconfig.ACConfig;
import de.cristelknight.cristellib.autoconfig.ACInfoData;
import de.cristelknight.cristellib.config.ConfigType;
import de.cristelknight.cristellib.config.serialize.ed.EDConfig;
import de.cristelknight.cristellib.config.serialize.ed.EDConfigTransformer;
import de.cristelknight.cristellib.config.serialize.ed.NestedEDConfig;
import de.cristelknight.cristellib.config.serialize.placement.PlacementConfig;
import de.cristelknight.cristellib.config.simple.ConfigRegistry;
import de.cristelknight.cristellib.config.client.simple.ClientConfigRegistry;
import de.cristelknight.cristellib.config.client.simple.SimpleConfigScreen;
import de.cristelknight.cristellib.config.client.simple.SimpleScreenBuilder;
import de.cristelknight.cristellib.util.Util;
import me.shedaniel.clothconfig2.api.ConfigBuilder;
import me.shedaniel.clothconfig2.api.ConfigCategory;
import me.shedaniel.clothconfig2.api.ConfigEntryBuilder;
import me.shedaniel.clothconfig2.gui.entries.BooleanListEntry;
import me.shedaniel.clothconfig2.gui.entries.DoubleListEntry;
import me.shedaniel.clothconfig2.gui.entries.IntegerListEntry;
import me.shedaniel.clothconfig2.impl.builders.SubCategoryBuilder;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.ClickEvent;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;

import java.net.URI;
import java.util.*;

@Environment(EnvType.CLIENT)
public class ScreenBuilder {

    private String modID;

    private final Set<ClientStructureConfig> clientStructureConfigs = new HashSet<>();

    public Screen create(Screen parent, String modID, boolean structure, boolean simple){
        this.modID = modID;
        ConfigBuilder builder = ConfigBuilder.create()
                .setTitle(Component.translatable("§7" + CristelLibExpectPlatform.getModDisplayName(modID) + " Configuration (via %s§7)", Util.CRISTEL_LIB));

        builder.setParentScreen(parent);
        builder.setSavingRunnable(this::onConfigSave);

        ConfigEntryBuilder entryBuilder = builder.entryBuilder();

        if(structure) {
            for(StructureConfig structureConfig : CristelLibRegistry.getConfigs().get(modID)){
                if(structureConfig.getType().equals(ConfigType.PLACEMENT)) addPlacementCategory(builder, structureConfig, entryBuilder);
                else addEDCategory(builder, structureConfig, entryBuilder);
            }
        }
        if(simple) {
            for(SimpleConfigScreen simpleConfigScreen : ClientConfigRegistry.getScreens(modID)) {
                SimpleScreenBuilder.addConfigToCategory(builder, entryBuilder, simpleConfigScreen);
            }
        }

        return builder.build();
    }

    private void addPlacementCategory(ConfigBuilder builder, StructureConfig structureConfig, ConfigEntryBuilder entryBuilder) {
        ConfigCategory placementCategory = builder.getOrCreateCategory(Component.translatable("cristellib.placementCategoryTitle"));


        if(structureConfig.isAutoGenerated && !ACInfoData.currentData.containsKey(modID)) placementCategory.addEntry(entryBuilder.startTextDescription(
                Component.translatable("cristellib.autoCategoryInfo", Util.CRISTEL_LIB).withStyle(s -> s.withClickEvent(new ClickEvent.OpenUrl(URI.create("https://github.com/Cristelknight999/Cristel-Lib/wiki/5.-Controlling-Structure-Auto-Config-(for-Mod-Authors)"))))
        ).build());

        Map<ResourceLocation, PlacementConfig> placementConfigs = structureConfig.placementConfig;
        Map<ResourceLocation, PlacementConfig> defaultPlacementConfigs = structureConfig.getDefaultStructurePlacement();

        Map<ResourceLocation, ClientPlacementConfig> clientPlacementConfigs = new HashMap<>();
        for (ResourceLocation structureSetName : Util.sortedKeyList(placementConfigs)) {
            PlacementConfig currentConfig = placementConfigs.get(structureSetName);
            PlacementConfig defaultConfig = defaultPlacementConfigs.get(structureSetName);
            if(defaultConfig == null) {
                getWarn(structureConfig, structureSetName);
                continue;
            }
            SubCategoryBuilder subCategory = entryBuilder.startSubCategory(Component.literal(structureConfig.toDefaultString(structureSetName)));

            ClientPlacementConfig clientPlacementConfig = new ClientPlacementConfig(
                    frequencyEntry(entryBuilder, "frequency", currentConfig.frequency(), defaultConfig.frequency(), subCategory),
                    intEntry(entryBuilder, "salt", currentConfig.salt(), defaultConfig.salt(), subCategory),
                    intEntry(entryBuilder, "separation", currentConfig.separation(), defaultConfig.separation(), subCategory),
                    intEntry(entryBuilder, "spacing", currentConfig.spacing(), defaultConfig.spacing(), subCategory)
            );

            placementCategory.addEntry(subCategory.build());

            clientPlacementConfigs.put(structureSetName, clientPlacementConfig);
        }
        clientStructureConfigs.add(new ClientStructureConfig(structureConfig, clientPlacementConfigs, null));
    }

    private void addEDCategory(ConfigBuilder builder, StructureConfig structureConfig, ConfigEntryBuilder entryBuilder) {
        ConfigCategory edCategory = builder.getOrCreateCategory(Component.translatable("cristellib.toggleCategoryTitle"));

        if(structureConfig.isAutoGenerated && !ACInfoData.currentData.containsKey(modID)) edCategory.addEntry(entryBuilder.startTextDescription(
                Component.translatable("cristellib.autoCategoryInfo", Util.CRISTEL_LIB).withStyle(s -> s.withClickEvent(new ClickEvent.OpenUrl(URI.create("https://github.com/Cristelknight999/Cristel-Lib/wiki/5.-Controlling-Structure-Auto-Config-(for-Mod-Authors)"))))
        ).build());

        Map<String, NestedEDConfig> nestedStructureMap = EDConfigTransformer.mapToNestedStructuresWithValues(structureConfig.enableDisableConfig, structureConfig);

        Map<ResourceLocation, ClientEDConfig> clientEDConfigs = new HashMap<>();
        for (String structureSetName : Util.sortedKeyList(nestedStructureMap)) {
            Map<String, BooleanListEntry> structures = new HashMap<>();
            SubCategoryBuilder rootSubCategory = entryBuilder.startSubCategory(Component.literal(structureSetName));
            NestedEDConfig nestedEDConfig = nestedStructureMap.get(structureSetName);

            if(!checkForSingle(nestedEDConfig, structureSetName, structureConfig, entryBuilder, structures, edCategory)) {
                addEDSubCategory(rootSubCategory, null, nestedEDConfig, "", entryBuilder, structures, structureConfig, structureSetName);
                edCategory.addEntry(rootSubCategory.build());
            }

            clientEDConfigs.put(structureConfig.toDefaultRL(structureSetName), new ClientEDConfig(structures));
        }

        clientStructureConfigs.add(new ClientStructureConfig(structureConfig, null, clientEDConfigs));
    }

    private boolean checkForSingle(NestedEDConfig nestedEDConfig, String structureSetName, StructureConfig structureConfig, ConfigEntryBuilder entryBuilder, Map<String, BooleanListEntry> structures, ConfigCategory edCategory) {
        if(nestedEDConfig.entries().size() != 1) return false;
        NestedEDConfig.Entry entry = nestedEDConfig.entries().values().stream().findAny().get();
        if(!entry.isBoolean()) return false;

        String key = nestedEDConfig.entries().keySet().stream().findAny().get();

        BooleanListEntry toggle = entryBuilder.startBooleanToggle(
                        Component.literal(key),
                        entry.value()
                ).setDefaultValue(true)
                .build();

        structures.put(key, toggle);

        if(getEDSubWarn(structureConfig, key, structureSetName)) return true;

        edCategory.addEntry(toggle);
        return true;
    }


    private void addEDSubCategory(SubCategoryBuilder rootCategory, SubCategoryBuilder parent, NestedEDConfig edConfig, String pathPrefix,
                                  ConfigEntryBuilder entryBuilder, Map<String, BooleanListEntry> structures, StructureConfig structureConfig, String structureSetName) {
        Map<String, NestedEDConfig.Entry> entries = edConfig.entries();
        for (String key : Util.sortedKeyList(entries)) {
            NestedEDConfig.Entry value = entries.get(key);
            String fullPath = pathPrefix.isEmpty() ? key : pathPrefix + "/" + key;

            if (value.isBoolean()) {
                // Simple toggle
                BooleanListEntry toggle = entryBuilder.startBooleanToggle(
                                Component.literal(key),
                                value.value()
                        ).setDefaultValue(true)
                        .build();

                structures.put(fullPath, toggle);

                if(getEDSubWarn(structureConfig, fullPath, structureSetName)) continue;

                if(parent == null) rootCategory.add(toggle);
                else parent.add(toggle);

            } else {
                // Nested structure → make subcategory
                SubCategoryBuilder subCategory = entryBuilder.startSubCategory(Component.literal(key));

                // Recursively build its children
                addEDSubCategory(rootCategory, subCategory, value.nested(), fullPath, entryBuilder, structures, structureConfig, structureSetName);

                if(parent == null) rootCategory.add(subCategory.build());
                else parent.add(subCategory.build());
            }
        }
    }

    // Saving
    private void onConfigSave(){
        for(ClientStructureConfig clientStructureConfig : clientStructureConfigs) {
            StructureConfig structureConfig = clientStructureConfig.structureConfig();
            if(structureConfig.getType().equals(ConfigType.PLACEMENT)) updatePlacements(clientStructureConfig.structureConfig(), clientStructureConfig.clientPlacementConfigs());
            else updateEDs(clientStructureConfig.structureConfig(), clientStructureConfig.clientEDConfigs());

            structureConfig.writeConfig(true);
            structureConfig.addSetsToRuntimePack();
        }

        SimpleScreenBuilder.saveConfigs(modID);
    }
    private void updatePlacements(StructureConfig structureConfig, Map<ResourceLocation, ClientPlacementConfig> clientPlacementConfigs) {
        Map<ResourceLocation, PlacementConfig> placementConfigs = structureConfig.placementConfig;
        for(ResourceLocation structureName : clientPlacementConfigs.keySet()) {
            placementConfigs.put(structureName, clientPlacementConfigs.get(structureName).toPlacement());
        }
    }
    private void updateEDs(StructureConfig structureConfig, Map<ResourceLocation, ClientEDConfig> clientEDConfigs){
        Map<ResourceLocation, EDConfig> placementConfigs = structureConfig.enableDisableConfig;
        for(ResourceLocation structureName : clientEDConfigs.keySet()) {
            placementConfigs.put(structureName, clientEDConfigs.get(structureName).toED());
        }
    }

    // Entry helpers
    private IntegerListEntry intEntry(ConfigEntryBuilder configEntry, String name, int value, int defaultValue, SubCategoryBuilder subCategory){
        IntegerListEntry intEntry = configEntry.startIntField(Component.literal(name), value).setDefaultValue(defaultValue).build();
        subCategory.add(intEntry);
        return intEntry;
    }

    private DoubleListEntry frequencyEntry(ConfigEntryBuilder configEntry, String name, double value, double defaultValue, SubCategoryBuilder subCategory){
        DoubleListEntry intEntry = configEntry.startDoubleField(Component.literal(name), value).setDefaultValue(defaultValue).setMin(0.000001).setMax(1.0).build();
        subCategory.add(intEntry);
        return intEntry;
    }

    // Warn helpers
    private static void getWarn(StructureConfig structureConfig, ResourceLocation structureSetName) {
        CristelLib.LOGGER.warn("Structure Set: {} has no default config, skipping!\nThis probably indicates that this config file is outdated and should be deleted to re-create it. (Path: {})", structureSetName.toString(), structureConfig.getPath());
    }

    private boolean getEDSubWarn(StructureConfig structureConfig, String fullPath, String structureSetName) {
        ResourceLocation setLocation = structureConfig.toDefaultRL(structureSetName);
        List<ResourceLocation> structures = structureConfig.getDefaultStructures().get(setLocation);
        if(structures == null) {
            getWarn(structureConfig, setLocation);
            return true;
        }
        if(!structures.contains(structureConfig.toDefaultRL(fullPath))) {
            CristelLib.LOGGER.warn("Structure: {} has no default config, skipping!\nThis probably indicates that this config file is outdated and should be deleted to re-create it. (Path: {})", fullPath, structureConfig.getPath());
            return true;
        }
        return false;
    }

    // Get correct screens helpers
    public static Pair<Boolean, Boolean> shouldCreateScreen(String modID, boolean mainStructure) {
        if(modID.equals(CristelLib.MOD_ID) || modID.equals("minecraft")) return new Pair<>(false, false);

        boolean structure = mainStructure &&
                CristelLibRegistry.getConfigs().containsKey(modID) &&
                !ConfigRegistry.get(ACConfig.class).clientExcludedMods().contains(modID);

        return new Pair<>(structure, ClientConfigRegistry.hasScreens(modID));
    }

    public static Set<String> allConfigMods(boolean structure) {
        Set<String> allMods = new HashSet<>(ClientConfigRegistry.getAllConfigsWithScreen().keySet());
        if(structure) allMods.addAll(new HashSet<>(CristelLibRegistry.getConfigs().keySet()));
        return allMods;
    }
}
