package de.cristelknight.cristellib.autoconfig;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import de.cristelknight.cristellib.CristelLib;
import de.cristelknight.cristellib.CristelLibRegistry;
import de.cristelknight.cristellib.StructureConfig;
import de.cristelknight.cristellib.config.ConfigType;
import de.cristelknight.cristellib.config.simple.ConfigRegistry;
import de.cristelknight.cristellib.util.JanksonUtil;
import de.cristelknight.cristellib.util.Util;
import net.minecraft.resources.Identifier;
import net.minecraft.util.GsonHelper;

import java.nio.file.Path;
import java.util.*;

public class ModFinder {
    
    public static final Set<String> supportedPlacements = Set.of("minecraft:random_spread",
            "moogs_structures:advanced_random_spread", "mes:advanced_random_spread", "mns:advanced_random_spread", "mss:advanced_random_spread", "mvs:advanced_random_spread",
            "repurposed_structures:advanced_random_spread"
    );
    
    public static void addAutoConfigs(String modID, Set<String> structureSets, Map<String, Set<StructureConfig>> structureConfigData, CristelLibRegistry registry) {
        Set<StructureConfig> configSet = new HashSet<>();

        boolean customPath = ACInfoData.currentData.containsKey(modID) && !ACInfoData.currentData.get(modID).autoConfigPath().isEmpty();
        String customSubPath = ConfigRegistry.get(ACConfig.class).autoConfigSubPath();

        StructureConfig edConfig = StructureConfig.createWithDefaultConfigPath(customPath ? ACInfoData.currentData.get(modID).autoConfigPath() : customSubPath + modID, "structure_toggle_config", ConfigType.ENABLE_DISABLE);
        StructureConfig placementConfig = StructureConfig.createWithDefaultConfigPath(customPath ? ACInfoData.currentData.get(modID).autoConfigPath() : customSubPath + modID, "structure_placement_config", ConfigType.PLACEMENT);

        structureSets.forEach(path -> {
            JsonElement e = JanksonUtil.getElement(modID, path);
            if(e != null) {

                JsonObject object = GsonHelper.convertToJsonObject(e, "Set at: " + path + " modId: " + modID).getAsJsonObject("placement");
                Identifier location = getLocation(Path.of(path));

                if(supportedPlacements.contains(GsonHelper.getAsString(object, "type"))) {
                    registry.registerSetToConfig(modID, location, edConfig, placementConfig);
                }
                else registry.registerSetToConfig(modID, location, edConfig);

            }
        });

        if(!placementConfig.isSetsEmpty()) configSet.add(placementConfig);
        if(!edConfig.isSetsEmpty()) configSet.add(edConfig);
        if(!configSet.isEmpty()) {
            configSet.forEach((config)-> {
                config.getDefaultNamespace();
                config.isAutoGenerated = true;
                config.setHeader("Automatically generated by Cristel Lib");
            });
            structureConfigData.put(modID, configSet);
        }
    }


    private static Identifier getLocation(Path rootPath) {
        String namespace = rootPath.getName(1).toString();
        String rawPath = Util.cutFileType(rootPath.subpath(4, rootPath.getNameCount()));
        String path = Util.normalizeResourcePath(rawPath);

        if(namespace.equals(CristelLib.MC_ID)) {
            return Identifier.withDefaultNamespace(path);
        }
        return Identifier.fromNamespaceAndPath(namespace, path);
    }

    public static boolean shouldSkipModForACPre(String modID, Set<String> modsWithConfig) {
        return modsWithConfig.contains(modID) || modID.equals(CristelLib.MC_ID);
    }

    public static boolean shouldSkipModForACAfter(String modID, Set<String> modsWithConfig) {
        ACConfig acConfig = ConfigRegistry.get(ACConfig.class);
        return acConfig.disableAutoConfig() || acConfig.blacklistedMods().contains(modID) || modsWithConfig.contains(modID);
    }
}
