package de.cristelknight.cristellib.autoconfig;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import de.cristelknight.cristellib.CristelLibExpectPlatform;
import de.cristelknight.cristellib.CristelLibRegistry;
import de.cristelknight.cristellib.StructureConfig;
import de.cristelknight.cristellib.config.ConfigType;
import de.cristelknight.cristellib.config.simple.ConfigRegistry;
import de.cristelknight.cristellib.data.PathFinder;
import de.cristelknight.cristellib.util.JanksonUtil;
import de.cristelknight.cristellib.util.Util;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.GsonHelper;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Stream;

public class ModFinder {
    
    public static Set<String> supportedPlacements = Set.of("minecraft:random_spread",
            "mes:advanced_random_spread", "mns:advanced_random_spread", "mss:advanced_random_spread", "mvs:advanced_random_spread",
            "repurposed_structures:advanced_random_spread"
    );
    
    public static void addConfigs(Map<String, Set<StructureConfig>> configs, CristelLibRegistry registry) {
        find(configs.keySet()).forEach((modID, structureSets) -> {
            Set<StructureConfig> configSet = new HashSet<>();

            boolean customPath = ACInfoData.currentData.containsKey(modID) && !ACInfoData.currentData.get(modID).autoConfigPath().isEmpty();
            StructureConfig edConfig = StructureConfig.createWithDefaultConfigPath(customPath ? ACInfoData.currentData.get(modID).autoConfigPath() : modID, "structure_toggle_config", ConfigType.ENABLE_DISABLE);
            StructureConfig placementConfig = StructureConfig.createWithDefaultConfigPath(customPath ? ACInfoData.currentData.get(modID).autoConfigPath() : modID, "structure_placement_config", ConfigType.PLACEMENT);

            structureSets.forEach(path -> {
                JsonElement e = JanksonUtil.getElement(modID, path.toString());
                JsonObject object = GsonHelper.convertToJsonObject(e, "Set at: " + path).getAsJsonObject("placement");
                ResourceLocation location = getLocation(path);
                if(supportedPlacements.contains(GsonHelper.getAsString(object, "type"))) {
                    registry.registerSetToConfig(modID, location, edConfig, placementConfig);
                }
                else registry.registerSetToConfig(modID, location, edConfig);
            });

            if(!placementConfig.isSetsEmpty()) configSet.add(placementConfig);
            if(!edConfig.isSetsEmpty()) configSet.add(edConfig);
            if(!configSet.isEmpty()) {
                configSet.forEach((config)-> {
                    config.getDefaultNamespace();
                    config.isAutoGenerated = true;
                    config.setHeader("Automatically generated by Cristel Lib");
                });
                configs.put(modID, configSet);
            }
        });
    }


    private static ResourceLocation getLocation(Path rootPath) {
        String namespace = rootPath.getName(1).toString();
        String path = Util.cutFileType(rootPath.subpath(4, rootPath.getNameCount()));

        if(namespace.equals("minecraft")) {
            return ResourceLocation.withDefaultNamespace(path);
        }
        return ResourceLocation.fromNamespaceAndPath(namespace, path);
    }

    public static Map<String, List<Path>> find(Set<String> modsWithConfig) {
        ACConfig acConfig = ConfigRegistry.get(ACConfig.class);
        if(acConfig.disableAutoConfig()) return Map.of();

        Map<String, List<Path>> structureSets = new HashMap<>();
        for(String modID : CristelLibExpectPlatform.getModIds()) {
            if(modsWithConfig.contains(modID) || modID.equals("minecraft") || acConfig.blacklistedMods().contains(modID)) continue;
            CristelLibExpectPlatform.getRootPaths(modID).forEach(rootPath -> structureSets.put(modID, findSets(rootPath)));
        }
        return structureSets;
    }

    private static List<Path> findSets(Path rootPath) {
        List<Path> structureSets = new ArrayList<>();
        Path dataDir = rootPath.resolve("data");
        if(!Files.exists(dataDir)) return structureSets;

        try (Stream<Path> namespaces = Files.list(dataDir)) {
            namespaces.filter(Files::isDirectory).forEach(namespace -> {
                Path structureSetDir = namespace.resolve("worldgen").resolve("structure_set");
                try {
                    PathFinder.walk(structureSetDir, Files::isDirectory, (path, file) -> {
                        if (Files.isRegularFile(file) && file.getFileName().toString().endsWith(".json")) {
                            structureSets.add(file);
                        }
                        return true;
                    }, true, Integer.MAX_VALUE);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }

            });
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return structureSets;
    }

}
